<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\fonts\css\font-awesome.css" />
    <None Include="wwwroot\fonts\css\font-awesome.min.css" />
    <None Include="wwwroot\fonts\fonts\fontawesome-webfont.eot" />
    <None Include="wwwroot\fonts\fonts\fontawesome-webfont.svg" />
    <None Include="wwwroot\fonts\fonts\fontawesome-webfont.ttf" />
    <None Include="wwwroot\fonts\fonts\fontawesome-webfont.woff" />
    <None Include="wwwroot\fonts\fonts\fontawesome-webfont.woff2" />
    <None Include="wwwroot\fonts\fonts\FontAwesome.otf" />
    <None Include="wwwroot\fonts\HELP-US-OUT.txt" />
    <None Include="wwwroot\fonts\less\animated.less" />
    <None Include="wwwroot\fonts\less\bordered-pulled.less" />
    <None Include="wwwroot\fonts\less\core.less" />
    <None Include="wwwroot\fonts\less\fixed-width.less" />
    <None Include="wwwroot\fonts\less\font-awesome.less" />
    <None Include="wwwroot\fonts\less\icons.less" />
    <None Include="wwwroot\fonts\less\larger.less" />
    <None Include="wwwroot\fonts\less\list.less" />
    <None Include="wwwroot\fonts\less\mixins.less" />
    <None Include="wwwroot\fonts\less\path.less" />
    <None Include="wwwroot\fonts\less\rotated-flipped.less" />
    <None Include="wwwroot\fonts\less\screen-reader.less" />
    <None Include="wwwroot\fonts\less\stacked.less" />
    <None Include="wwwroot\fonts\less\variables.less" />
    <None Include="wwwroot\fonts\scss\font-awesome.scss" />
    <None Include="wwwroot\fonts\scss\_animated.scss" />
    <None Include="wwwroot\fonts\scss\_bordered-pulled.scss" />
    <None Include="wwwroot\fonts\scss\_core.scss" />
    <None Include="wwwroot\fonts\scss\_fixed-width.scss" />
    <None Include="wwwroot\fonts\scss\_icons.scss" />
    <None Include="wwwroot\fonts\scss\_larger.scss" />
    <None Include="wwwroot\fonts\scss\_list.scss" />
    <None Include="wwwroot\fonts\scss\_mixins.scss" />
    <None Include="wwwroot\fonts\scss\_path.scss" />
    <None Include="wwwroot\fonts\scss\_rotated-flipped.scss" />
    <None Include="wwwroot\fonts\scss\_screen-reader.scss" />
    <None Include="wwwroot\fonts\scss\_stacked.scss" />
    <None Include="wwwroot\fonts\scss\_variables.scss" />
    <None Include="wwwroot\images\alertPic.jpg" />
    <None Include="wwwroot\images\apart1.jpg" />
    <None Include="wwwroot\images\apart2.jpg" />
    <None Include="wwwroot\images\apart3.jpeg" />
    <None Include="wwwroot\images\banner1.jpg" />
    <None Include="wwwroot\images\banner1_OLD.jpg" />
    <None Include="wwwroot\images\BOGhouseBanner.jpg" />
    <None Include="wwwroot\images\BOGhouseBanner_OLD.jpg" />
    <None Include="wwwroot\images\cabin1.jpg" />
    <None Include="wwwroot\images\cabin2.jpg" />
    <None Include="wwwroot\images\cabin3.jpg" />
    <None Include="wwwroot\images\cabin4.jpg" />
    <None Include="wwwroot\images\condo1.jpg" />
    <None Include="wwwroot\images\condo2.jpg" />
    <None Include="wwwroot\images\cottage1.jpg" />
    <None Include="wwwroot\images\dark_tint.png" />
    <None Include="wwwroot\images\default-house.jpg" />
    <None Include="wwwroot\images\house1.jpg" />
    <None Include="wwwroot\images\house2.jpg" />
    <None Include="wwwroot\images\house3.jpg" />
    <None Include="wwwroot\images\log-cabin.jpg" />
    <None Include="wwwroot\images\Thumbs.db" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.0" />
  </ItemGroup>

</Project>
