
# Used to specify which startup profile to use.  
# Must be one of: dev, test, stage, prod
#
spring.profiles.active=stage

# 
# Used to specify at startup which port the 
# server should listen on for transfer and
# query requests
#
server.port=8081
