
# Used to specify which startup profile to use.  
# Must be one of: dev, test, stage, prod, sim
#
# NOTE: 'service' should be included by default as it is
# used to include service layer configuration specified
# in 'application-service.properties' for each service
# that has this property file configured.
#
spring.profiles.active=dev

# 
# Used to specify at startup which port the 
# server should listen on for transfer and
# query requests
#
server.port=8080
